blank_issues_enabled: false
contact_links:
  - name: Discussions Forum
    url: https://github.com/ptr727/PlexCleaner/discussions
    about: Please ask general questions and prose enhancements in the Discussions forum.
