name: 'Build and Push Docker Images Pipeline'

on:
  push:
    # multiarch test branch only
    branches: [ multiarch ]
  workflow_dispatch:

jobs:

  buildpush:

    name: 'Build and Push Docker Images'
    runs-on: ubuntu-latest

    steps:

      # Checkout code
      # https://github.com/marketplace/actions/checkout
      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Get all history for version calculation
          fetch-depth: 0

      # Run Nerdbank.GitVersioning
      # https://github.com/marketplace/actions/nerdbank-gitversioning
      - name: 'Run Nerdbank.GitVersioning Tool'
        id: nbgv
        uses: dotnet/nbgv@master

      # Setup QEMU for multi architecture builds
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: 'Setup QEMU'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # Setup docker build
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # Login to Docker Hub
      # https://github.com/marketplace/actions/docker-login
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Login to GitHub Container Registry
      # https://github.com/marketplace/actions/docker-login
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker build and push
      # https://github.com/marketplace/actions/build-and-push-docker-images

      # Debian: linux/amd64,linux/arm64,linux/arm/v7
      - name: 'Docker Build and Push - Debian.dotNET'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Debian.dotNET.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ (github.event_name != 'pull_request') }}
          build-args: |
            LABEL_VERSION=${{ steps.nbgv.outputs.SemVer2 }}
            BUILD_CONFIGURATION=${{ endsWith(github.ref, 'refs/heads/main') && 'Release' || 'Debug' }}
            BUILD_VERSION=${{ steps.nbgv.outputs.AssemblyVersion }}
            BUILD_FILE_VERSION=${{ steps.nbgv.outputs.AssemblyFileVersion }}
            BUILD_ASSEMBLY_VERSION=${{ steps.nbgv.outputs.AssemblyFileVersion }}
            BUILD_INFORMATION_VERSION=${{ steps.nbgv.outputs.AssemblyInformationalVersion }}
            BUILD_PACKAGE_VERSION=${{ steps.nbgv.outputs.SemVer2 }}
          tags: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'debian' || 'debian-develop' }}
            ghcr.io/${{ github.repository_owner }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'debian' || 'debian-develop' }}

      # Alpine: linux/amd64,linux/arm64
      - name: 'Docker Build and Push - Alpine.dotNET'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Alpine.dotNET.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ (github.event_name != 'pull_request') }}
          build-args: |
            LABEL_VERSION=${{ steps.nbgv.outputs.SemVer2 }}
            BUILD_CONFIGURATION=${{ endsWith(github.ref, 'refs/heads/main') && 'Release' || 'Debug' }}
            BUILD_VERSION=${{ steps.nbgv.outputs.AssemblyVersion }}
            BUILD_FILE_VERSION=${{ steps.nbgv.outputs.AssemblyFileVersion }}
            BUILD_ASSEMBLY_VERSION=${{ steps.nbgv.outputs.AssemblyFileVersion }}
            BUILD_INFORMATION_VERSION=${{ steps.nbgv.outputs.AssemblyInformationalVersion }}
            BUILD_PACKAGE_VERSION=${{ steps.nbgv.outputs.SemVer2 }}
          tags: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'alpine' || 'alpine-develop' }}
            ghcr.io/${{ github.repository_owner }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'alpine' || 'alpine-develop' }}

      # Ubuntu: linux/amd64
      - name: 'Docker Build and Push - Ubuntu.dotNET.Savoury'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Ubuntu.dotNET.Savoury.Dockerfile
          platforms: linux/amd64
          push: ${{ (github.event_name != 'pull_request') }}
          secrets: |
            "savoury_ppa_auth=${{ secrets.SAVOURY_PPA_AUTH }}"
          build-args: |
            LABEL_VERSION=${{ steps.nbgv.outputs.SemVer2 }}
            BUILD_CONFIGURATION=${{ endsWith(github.ref, 'refs/heads/main') && 'Release' || 'Debug' }}
            BUILD_VERSION=${{ steps.nbgv.outputs.AssemblyVersion }}
            BUILD_FILE_VERSION=${{ steps.nbgv.outputs.AssemblyFileVersion }}
            BUILD_ASSEMBLY_VERSION=${{ steps.nbgv.outputs.AssemblyFileVersion }}
            BUILD_INFORMATION_VERSION=${{ steps.nbgv.outputs.AssemblyInformationalVersion }}
            BUILD_PACKAGE_VERSION=${{ steps.nbgv.outputs.SemVer2 }}
          tags: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'savoury' || 'savoury-develop' }}
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'latest' || 'develop' }}
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ steps.nbgv.outputs.SemVer2 }}
            ghcr.io/${{ github.repository_owner }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'savoury' || 'savoury-develop' }}
            ghcr.io/${{ github.repository_owner }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'latest' || 'develop' }}
            ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ steps.nbgv.outputs.SemVer2 }}

  # Update Docker Hub description
  hubdescription:

    needs: buildpush
    name: 'Update Docker Hub Description'
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/docker-hub-description
      - name: 'Update Docker Hub Description'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ptr727/plexcleaner
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./Docker/README.md

  # Create a custom badge to report the build date
  # Run this job at the end of the pipeline
  datebadge:

    needs: hubdescription
    name: 'Build Date Badge'
    runs-on: ubuntu-latest

    steps:
      # Get date from environment as a variable
      - id: date
        run: |
          echo "date=$(date)" >> $GITHUB_OUTPUT
      # Create badge
      # https://github.com/marketplace/actions/bring-your-own-badge
      - name: 'Build Date Badge'
        uses: RubbaBoy/BYOB@v1
        with:
          NAME: lastbuild
          LABEL: "Last Build"
          ICON: "github"
          STATUS: ${{ steps.date.outputs.date }}
          COLOR: "blue"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
