# TODO : Consolidate BuildPublishPipeline.yml and BuildDockerPipeline.yml

name: 'Build and Push Docker Image Pipeline'

on:
  push:
    branches: [ main, develop ]
    paths-ignore: [ 'README.md' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Rebuild docker container 2am every Monday
    - cron: '0 2 * * MON'

jobs:

  buildpush:
    name: 'Build and Push Docker Image Pipeline'
    runs-on: ubuntu-latest

    steps:

      # Install .NET SDK
      # https://github.com/marketplace/actions/setup-net-core-sdk
      - name: 'Setup .NET SDK 7'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Checkout code
      # https://github.com/marketplace/actions/checkout
      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          # Get all history for version calculation
          fetch-depth: 0

      # Run Nerdbank.GitVersioning
      # https://github.com/marketplace/actions/nerdbank-gitversioning
      - name: 'Run Nerdbank.GitVersioning Tool'
        id: nbgv
        uses: dotnet/nbgv@master

      # Run Unit Tests
      # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test
      - name: 'Run Unit Tests'
        run: dotnet test ./PlexCleanerTests/PlexCleanerTests.csproj

      # Build and publish project to ./Docker/PlexCleaner
      # Set version information attributes
      # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
      - name: 'Build Project linux-x64'
        run: >-
            dotnet publish ./PlexCleaner/PlexCleaner.csproj
            --runtime linux-x64
            --self-contained false
            --output ./Docker/PlexCleaner
            --configuration ${{ endsWith(github.ref, 'refs/heads/main') && 'Release' || 'Debug' }}
            -property:Version=${{ steps.nbgv.outputs.AssemblyVersion }}
            -property:FileVersion=${{ steps.nbgv.outputs.AssemblyFileVersion }}
            -property:AssemblyVersion=${{ steps.nbgv.outputs.AssemblyVersion }}
            -property:InformationalVersion=${{ steps.nbgv.outputs.AssemblyInformationalVersion }}
            -property:PackageVersion=${{ steps.nbgv.outputs.SemVer2 }}

      # Setup docker build
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      # https://github.com/marketplace/actions/docker-login
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Login to GitHub Container Registry
      # https://github.com/marketplace/actions/docker-login
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker build and push
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: 'Docker Build and Push'
        uses: docker/build-push-action@v4
        with:
          context: ./Docker
          file: ./Docker/Dockerfile
          platforms: linux/amd64
          # Do not push on pull requests
          push: ${{ (github.event_name != 'pull_request') }}
          build-args: |
            LABEL_VERSION=${{ steps.nbgv.outputs.SemVer2 }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'latest' || 'develop' }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/plexcleaner:${{ steps.nbgv.outputs.SemVer2 }}
            ghcr.io/${{ github.repository_owner }}/plexcleaner:${{ endsWith(github.ref, 'refs/heads/main') && 'latest' || 'develop' }}
            ghcr.io/${{ github.repository_owner }}/plexcleaner:${{ steps.nbgv.outputs.SemVer2 }}

  # Create a custom badge to report the build date
  # Run this job at the end of the pipeline
  datebadge:
    needs: buildpush
    name: "Build Date Badge"
    runs-on: ubuntu-latest
    steps:
      # Get date from environment as a variable
      - id: date
        run: |
          echo "date=$(date)" >> $GITHUB_OUTPUT
      # Create badge
      # https://github.com/marketplace/actions/bring-your-own-badge
      - name: "Build Date Badge"
        uses: RubbaBoy/BYOB@v1
        with:
          NAME: lastbuild
          LABEL: "Last Build"
          ICON: "github"
          STATUS: ${{ steps.date.outputs.date }}
          COLOR: "blue"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
