name: 'Test'

on:
  push:
    branches: [ toolversions ]
  workflow_dispatch:
  
jobs:

  # Update Docker Hub description
  toolversions:

    name: 'Get Image Tool Versions'
    runs-on: ubuntu-latest

    strategy:

      matrix:
        include:
          - tag: ${{ endsWith(github.ref, 'refs/heads/main') && 'debian' || 'debian-develop' }}
          - tag: ${{ endsWith(github.ref, 'refs/heads/main') && 'alpine' || 'alpine-develop' }}
          - tag: ${{ endsWith(github.ref, 'refs/heads/main') && 'savoury' || 'savoury-develop' }}
          - tag: ${{ endsWith(github.ref, 'refs/heads/main') && 'arch' || 'arch-develop' }}

    steps:

    - name: Checkout 
      uses: actions/checkout@v3
  
    - name: Get Versions
      uses: addnab/docker-run-action@v3
      with:
        image: docker.io/ptr727/plexcleaner:${{ matrix.tag }}
        options: --volume ${{ github.workspace }}:/workspace
        run: |
          echo PlexCleaner: $(/PlexCleaner/PlexCleaner --version) > /workspace/${{ matrix.tag }}
          echo dotNET: $(dotnet --version) >> /workspace/${{ matrix.tag }}
          echo HandBrakeCLI: $(HandBrakeCLI --version) >> /workspace/${{ matrix.tag }}
          echo MediaInfo: $(mediainfo --version) >> /workspace/${{ matrix.tag }}
          echo MkvMerge: $(mkvmerge --version) >> /workspace/${{ matrix.tag }}
          echo FfMpeg: $(ffmpeg -version) >> /workspace/${{ matrix.tag }}

    - name: Print Versions
      run: cat ${{ github.workspace }}/${{ matrix.tag }}

  # Update Docker Hub description
  updatereadme:

    name: 'Update README.md'
    runs-on: ubuntu-latest
    needs: toolversions

    steps:
        
    # https://blog.ediri.io/how-to-automate-your-github-profile-readme
    # https://github.com/marketplace/actions/generate-update-markdown-content

    # https://github.com/marketplace/actions/generate-update-markdown-content
    # https://github.com/muesli/markscribe
    - name: Update README.md from Template
      uses: muesli/readme-scribe@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        template: "./Docker/README.md.tpl"
        writeTo: "./Docker/README.md"

    # https://github.com/marketplace/actions/git-auto-commit
    - name: Commit README.md
      uses: stefanzweifel/git-auto-commit-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commit_message: Update generated README.md

# TODO: How to include file content?
# https://github.com/muesli/markscribe/issues/74