name: 'Update Docker Hub Description'

on:
  push:
    # Only update main branch
    branches: [ main ]
    paths:
      - README.md
      - .github/workflows/UpdateDockerHubDescription.yml
  workflow_dispatch:

jobs:
  description:
    name: 'Update Docker Hub Description'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Code'
        uses: actions/checkout@v2

      - name: 'Update Docker Hub Description'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ptr727/plexcleaner
